version: '2'
services:
  api:
    build: site/.
    image: mattiashem/know-site
    volumes:
      - ./site/:/code
    environment:
      - sites=www.alamo.co.uk,www.enterprise.com
      - sleep=3600
    #command: tail -f /etc/fstab
  mongo:
    image: mongo
  redis:
    image: redis
